import os
import shutil

def show_gpt_output(target_dir: str, file: str, docstrings: str):
    """
    Writes the generated docstrings to a file in the specified directory.
    
    This function checks if the output directory exists and creates it if it doesn't. It then writes the
    generated docstrings to a file in this directory. This ensures that the output directory always contains
    the latest docstrings generated by the GPT API.
    
    Args:
        target_dir (str): The directory where the output file will be written.
        file (str): The name of the output file.
        docstrings (str): The generated docstrings to be written to the file.
    """
    dest_path = os.path.join(target_dir, 'gpt_output')
    if not os.path.exists(dest_path):
        os.makedirs(dest_path, exist_ok=True)
    with open(os.path.join(dest_path, file), "w") as file1:
        file1.write(docstrings)
